Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./config", "/config"

  config.vm.define "database" do |database|

    database.vm.provider "virtualbox" do |vb|
      vb.name = "database"
      vb.cpus = 1
      vb.memory = 512
    end

    database.vm.network "private_network", ip: "192.168.33.11"
  
    database.vm.provision "ansible" do |ansible|
      ansible.playbook = "./config/ansible/playbook-mysql.yml"
    end
  
  end

  config.vm.define "application" do |application|

    application.vm.provider "virtualbox" do |vb|
      vb.name = "application"
      vb.cpus = 2
      vb.memory = 1024
    end
  
    application.vm.network "private_network", ip: "192.168.33.12" 
    application.vm.provision "shell",
      inline: "apt-get update && apt-get install -y puppet"

    application.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./config/manifests"
      puppet.manifest_file = "application.pp"
    end

  end

  config.vm.define "memcached" do |memcached|

    memcached.vm.provider "virtualbox" do |vb|
      vb.name = "memcached"
      vb.cpus = 1
      vb.memory = 512
    end

    memcached.vm.box = "centos/7"

    memcached.vm.network "private_network", ip: "192.168.33.13" 

  end

end
