Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  # Forwarded Port = NAT
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # Private Network = Host Only
  # config.vm.network "private_network", ip: "192.168.50.4"
  # config.vm.network "private_network", type: "dhcp"
  # Public Network = Bridge
  config.vm.network "public_network"
end
