Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./config", "/config"
  
  config.vm.provision "shell", path: "./config/provision.sh"

end
